name: sparsifiedSGD
channels:
  - defaults
dependencies:
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - attrs=18.2.0
  - automat=0.7.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=2.1.4
  - bzip2=1.0.6
  - ca-certificates=2018.03.07
  - cairo=1.14.12
  - certifi=2018.8.24
  - cffi=1.11.5
  - click=6.7
  - click-plugins=1.0.3
  - cligj=0.4.0
  - constantly=15.1.0
  - cryptography=2.3.1
  - curl=7.61.0
  - cycler=0.10.0
  - dbus=1.13.2
  - decorator=4.3.0
  - descartes=1.1.0
  - entrypoints=0.2.3
  - expat=2.2.6
  - fiona=1.7.10
  - fontconfig=2.13.0
  - freetype=2.9.1
  - freexl=1.0.5
  - gdal=2.2.2
  - geopandas=0.3.0
  - geos=3.6.2
  - giflib=5.1.4
  - glib=2.56.2
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf4=4.2.13
  - hdf5=1.10.2
  - html5lib=1.0.1
  - hyperlink=18.0.0
  - icu=58.2
  - idna=2.7
  - incremental=17.5.0
  - intel-openmp=2019.0
  - ipykernel=4.10.0
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - jedi=0.12.1
  - jinja2=2.10
  - jpeg=9b
  - json-c=0.13.1
  - jsonschema=2.6.0
  - jupyter_client=5.2.3
  - jupyter_core=4.4.0
  - jupyterlab=0.34.9
  - jupyterlab_launcher=0.13.1
  - kealib=1.4.7
  - kiwisolver=1.0.1
  - krb5=1.16.1
  - libboost=1.67.0
  - libcurl=7.61.0
  - libdap4=3.19.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgdal=2.2.4
  - libgfortran-ng=7.3.0
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libpng=1.6.35
  - libpq=10.5
  - libprotobuf=3.6.0
  - libsodium=1.0.16
  - libspatialindex=1.8.5
  - libspatialite=4.3.0a
  - libssh2=1.8.0
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.9
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.8
  - markdown=2.6.11
  - markupsafe=1.0
  - matplotlib=3.0.0
  - mistune=0.8.3
  - mkl=2019.0
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - munch=2.3.2
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.6.0
  - numpy=1.15.2
  - numpy-base=1.15.2
  - openjpeg=2.3.0
  - openssl=1.0.2p
  - pandas=0.23.4
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.3.1
  - patsy=0.5.0
  - pcre=8.42
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pip=10.0.1
  - pixman=0.34.0
  - poppler=0.65.0
  - poppler-data=0.4.9
  - proj4=5.0.1
  - prometheus_client=0.3.1
  - prompt_toolkit=1.0.15
  - protobuf=3.6.0
  - psycopg2=2.7.5
  - ptyprocess=0.6.0
  - pyasn1=0.4.4
  - pyasn1-modules=0.2.2
  - pycparser=2.19
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pyparsing=2.2.1
  - pyproj=1.9.5.1
  - pyqt=5.9.2
  - pysal=1.14.4.post1
  - python=3.5.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - pyzmq=17.1.2
  - qt=5.9.6
  - readline=7.0
  - rtree=0.8.3
  - scikit-learn=0.20.0
  - scipy=1.1.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - service_identity=17.0.0
  - setuptools=40.2.0
  - shapely=1.6.4
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.11.0
  - sqlalchemy=1.2.11
  - sqlite=3.25.2
  - statsmodels=0.9.0
  - tensorboard=1.10.0
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.8
  - tornado=5.1.1
  - traitlets=4.3.2
  - twisted=18.7.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.14.1
  - wheel=0.31.1
  - xerces-c=3.2.2
  - xz=5.2.4
  - zeromq=4.2.5
  - zlib=1.2.11
  - zope=1.0
  - zope.interface=4.5.0
prefix: /home/cordonni/.conda/envs/sparsifiedSGD

