name: sparsifiedSGD
channels:
  - defaults
dependencies:
  - appdirs=1.4.3=py35h28b3542_0
  - asn1crypto=0.24.0=py35_0
  - attrs=18.2.0=py35h28b3542_0
  - automat=0.7.0=py35_0
  - backcall=0.1.0=py35_0
  - blas=1.0=mkl
  - bleach=2.1.4=py35_0
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2018.03.07=0
  - cairo=1.14.12=h8948797_3
  - certifi=2018.8.24=py35_1
  - cffi=1.11.5=py35he75722e_1
  - click=6.7=py35h353a69f_0
  - click-plugins=1.0.3=py35_1
  - cligj=0.4.0=py35_1
  - constantly=15.1.0=py35h28b3542_0
  - cryptography=2.3.1=py35hc365091_0
  - curl=7.61.0=h84994c4_0
  - cycler=0.10.0=py35hc4d5149_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py35_0
  - descartes=1.1.0=py35h2f9c1c0_0
  - entrypoints=0.2.3=py35_2
  - expat=2.2.6=he6710b0_0
  - fiona=1.7.10=py35h82be5b1_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - freexl=1.0.5=h14c3975_0
  - gdal=2.2.2=py35h40af447_1
  - geopandas=0.3.0=py35h2f9c1c0_0
  - geos=3.6.2=heeff764_2
  - giflib=5.1.4=h14c3975_1
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.2=hba1933b_1
  - html5lib=1.0.1=py35_0
  - hyperlink=18.0.0=py35_0
  - icu=58.2=h9c2bf20_1
  - idna=2.7=py35_0
  - incremental=17.5.0=py35_0
  - intel-openmp=2019.0=118
  - ipykernel=4.10.0=py35_0
  - ipython=6.5.0=py35_0
  - ipython_genutils=0.2.0=py35hc9e07d0_0
  - jedi=0.12.1=py35_0
  - jinja2=2.10=py35_0
  - jpeg=9b=h024ee3a_2
  - json-c=0.13.1=h1bed415_0
  - jsonschema=2.6.0=py35h4395190_0
  - jupyter_client=5.2.3=py35_0
  - jupyter_core=4.4.0=py35_0
  - jupyterlab=0.34.9=py35_0
  - jupyterlab_launcher=0.13.1=py35_0
  - kealib=1.4.7=h77bc034_6
  - kiwisolver=1.0.1=py35hf484d3e_0
  - krb5=1.16.1=hc83ff2d_6
  - libboost=1.67.0=h46d08c1_4
  - libcurl=7.61.0=h1ad7b7a_0
  - libdap4=3.19.1=h6ec2957_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgdal=2.2.4=h6f639c0_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libkml=1.3.0=h590aaf7_4
  - libnetcdf=4.6.1=h10edf3e_1
  - libpng=1.6.35=hbc83047_0
  - libpq=10.5=h1ad7b7a_0
  - libprotobuf=3.6.0=hdbcaa40_0
  - libsodium=1.0.16=h1bed415_0
  - libspatialindex=1.8.5=h20b78c2_2
  - libspatialite=4.3.0a=he475c7f_19
  - libssh2=1.8.0=h9cfc8f7_4
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - markdown=2.6.11=py35_0
  - markupsafe=1.0=py35h14c3975_1
  - matplotlib=3.0.0=py35h5429711_0
  - mistune=0.8.3=py35h14c3975_1
  - mkl=2019.0=118
  - mkl_fft=1.0.6=py35h7dd41cf_0
  - mkl_random=1.0.1=py35h4414c95_1
  - munch=2.3.2=py35_0
  - nbconvert=5.3.1=py35_0
  - nbformat=4.4.0=py35h12e6e07_0
  - ncurses=6.1=hf484d3e_0
  - notebook=5.6.0=py35_0
  - numpy=1.15.2=py35h1d66e8a_0
  - numpy-base=1.15.2=py35h81de0dd_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.0.2p=h14c3975_0
  - pandas=0.23.4=py35h04863e7_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py35_1
  - parso=0.3.1=py35_0
  - patsy=0.5.0=py35_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py35_0
  - pickleshare=0.7.4=py35hd57304d_0
  - pip=10.0.1=py35_0
  - pixman=0.34.0=hceecf20_3
  - poppler=0.65.0=h581218d_1
  - poppler-data=0.4.9=0
  - proj4=5.0.1=h14c3975_0
  - prometheus_client=0.3.1=py35h28b3542_0
  - prompt_toolkit=1.0.15=py35hc09de7a_0
  - protobuf=3.6.0=py35hf484d3e_0
  - psycopg2=2.7.5=py35hb7f436b_0
  - ptyprocess=0.6.0=py35_0
  - pyasn1=0.4.4=py35h28b3542_0
  - pyasn1-modules=0.2.2=py35_0
  - pycparser=2.19=py35_0
  - pygments=2.2.0=py35h0f41973_0
  - pyopenssl=18.0.0=py35_0
  - pyparsing=2.2.1=py35_0
  - pyproj=1.9.5.1=py35_0
  - pyqt=5.9.2=py35h05f1152_2
  - pysal=1.14.4.post1=py35_1
  - python=3.5.6=hc3d631a_0
  - python-dateutil=2.7.3=py35_0
  - pytz=2018.5=py35_0
  - pyzmq=17.1.2=py35h14c3975_0
  - qt=5.9.6=h8703b6f_2
  - readline=7.0=h7b6447c_5
  - rtree=0.8.3=py35h2f9c1c0_0
  - scikit-learn=0.20.0=py35h4989274_1
  - scipy=1.1.0=py35hfa4b5c9_1
  - seaborn=0.9.0=py35_0
  - send2trash=1.5.0=py35_0
  - service_identity=17.0.0=py35h28b3542_0
  - setuptools=40.2.0=py35_0
  - shapely=1.6.4=py35h7ef4460_0
  - simplegeneric=0.8.1=py35_2
  - sip=4.19.8=py35hf484d3e_0
  - six=1.11.0=py35_1
  - sqlalchemy=1.2.11=py35h7b6447c_0
  - sqlite=3.25.2=h7b6447c_0
  - statsmodels=0.9.0=py35h3010b51_0
  - tensorboard=1.10.0=py35hf484d3e_0
  - terminado=0.8.1=py35_1
  - testpath=0.3.1=py35had42eaf_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py35h7b6447c_0
  - traitlets=4.3.2=py35ha522a97_0
  - twisted=18.7.0=py35h14c3975_1
  - wcwidth=0.1.7=py35hcd08066_0
  - webencodings=0.5.1=py35_1
  - werkzeug=0.14.1=py35_0
  - wheel=0.31.1=py35_0
  - xerces-c=3.2.2=h780794e_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.2.5=hf484d3e_1
  - zlib=1.2.11=ha838bed_2
  - zope=1.0=py35_1
  - zope.interface=4.5.0=py35h14c3975_0
prefix: /home/cordonni/.conda/envs/sparsifiedSGD

